# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/guidob/Escritorio/Taller de Programación 1/Argentum/Taller-TP-Final"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/guidob/Escritorio/Taller de Programación 1/Argentum/Taller-TP-Final"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/guidob/Escritorio/Taller de Programación 1/Argentum/Taller-TP-Final/CMakeFiles" "/home/guidob/Escritorio/Taller de Programación 1/Argentum/Taller-TP-Final/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/guidob/Escritorio/Taller de Programación 1/Argentum/Taller-TP-Final/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pruebasss

# Build rule for target.
pruebasss: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pruebasss
.PHONY : pruebasss

# fast build rule for target.
pruebasss/fast:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/build
.PHONY : pruebasss/fast

#=============================================================================
# Target rules for targets named prueba

# Build rule for target.
prueba: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prueba
.PHONY : prueba

# fast build rule for target.
prueba/fast:
	$(MAKE) -f CMakeFiles/prueba.dir/build.make CMakeFiles/prueba.dir/build
.PHONY : prueba/fast

Banker.o: Banker.cpp.o

.PHONY : Banker.o

# target to build an object file
Banker.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Banker.cpp.o
.PHONY : Banker.cpp.o

Banker.i: Banker.cpp.i

.PHONY : Banker.i

# target to preprocess a source file
Banker.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Banker.cpp.i
.PHONY : Banker.cpp.i

Banker.s: Banker.cpp.s

.PHONY : Banker.s

# target to generate assembly for a file
Banker.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Banker.cpp.s
.PHONY : Banker.cpp.s

Camera.o: Camera.cpp.o

.PHONY : Camera.o

# target to build an object file
Camera.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Camera.cpp.o
.PHONY : Camera.cpp.o

Camera.i: Camera.cpp.i

.PHONY : Camera.i

# target to preprocess a source file
Camera.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Camera.cpp.i
.PHONY : Camera.cpp.i

Camera.s: Camera.cpp.s

.PHONY : Camera.s

# target to generate assembly for a file
Camera.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Camera.cpp.s
.PHONY : Camera.cpp.s

ClientConnector.o: ClientConnector.cpp.o

.PHONY : ClientConnector.o

# target to build an object file
ClientConnector.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/ClientConnector.cpp.o
.PHONY : ClientConnector.cpp.o

ClientConnector.i: ClientConnector.cpp.i

.PHONY : ClientConnector.i

# target to preprocess a source file
ClientConnector.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/ClientConnector.cpp.i
.PHONY : ClientConnector.cpp.i

ClientConnector.s: ClientConnector.cpp.s

.PHONY : ClientConnector.s

# target to generate assembly for a file
ClientConnector.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/ClientConnector.cpp.s
.PHONY : ClientConnector.cpp.s

ClientController.o: ClientController.cpp.o

.PHONY : ClientController.o

# target to build an object file
ClientController.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/ClientController.cpp.o
.PHONY : ClientController.cpp.o

ClientController.i: ClientController.cpp.i

.PHONY : ClientController.i

# target to preprocess a source file
ClientController.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/ClientController.cpp.i
.PHONY : ClientController.cpp.i

ClientController.s: ClientController.cpp.s

.PHONY : ClientController.s

# target to generate assembly for a file
ClientController.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/ClientController.cpp.s
.PHONY : ClientController.cpp.s

ClientProtocol.o: ClientProtocol.cpp.o

.PHONY : ClientProtocol.o

# target to build an object file
ClientProtocol.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/ClientProtocol.cpp.o
.PHONY : ClientProtocol.cpp.o

ClientProtocol.i: ClientProtocol.cpp.i

.PHONY : ClientProtocol.i

# target to preprocess a source file
ClientProtocol.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/ClientProtocol.cpp.i
.PHONY : ClientProtocol.cpp.i

ClientProtocol.s: ClientProtocol.cpp.s

.PHONY : ClientProtocol.s

# target to generate assembly for a file
ClientProtocol.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/ClientProtocol.cpp.s
.PHONY : ClientProtocol.cpp.s

EmptyException.o: EmptyException.cpp.o

.PHONY : EmptyException.o

# target to build an object file
EmptyException.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/EmptyException.cpp.o
.PHONY : EmptyException.cpp.o

EmptyException.i: EmptyException.cpp.i

.PHONY : EmptyException.i

# target to preprocess a source file
EmptyException.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/EmptyException.cpp.i
.PHONY : EmptyException.cpp.i

EmptyException.s: EmptyException.cpp.s

.PHONY : EmptyException.s

# target to generate assembly for a file
EmptyException.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/EmptyException.cpp.s
.PHONY : EmptyException.cpp.s

Entity.o: Entity.cpp.o

.PHONY : Entity.o

# target to build an object file
Entity.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Entity.cpp.o
.PHONY : Entity.cpp.o

Entity.i: Entity.cpp.i

.PHONY : Entity.i

# target to preprocess a source file
Entity.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Entity.cpp.i
.PHONY : Entity.cpp.i

Entity.s: Entity.cpp.s

.PHONY : Entity.s

# target to generate assembly for a file
Entity.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Entity.cpp.s
.PHONY : Entity.cpp.s

EntityManager.o: EntityManager.cpp.o

.PHONY : EntityManager.o

# target to build an object file
EntityManager.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/EntityManager.cpp.o
.PHONY : EntityManager.cpp.o

EntityManager.i: EntityManager.cpp.i

.PHONY : EntityManager.i

# target to preprocess a source file
EntityManager.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/EntityManager.cpp.i
.PHONY : EntityManager.cpp.i

EntityManager.s: EntityManager.cpp.s

.PHONY : EntityManager.s

# target to generate assembly for a file
EntityManager.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/EntityManager.cpp.s
.PHONY : EntityManager.cpp.s

EventManager.o: EventManager.cpp.o

.PHONY : EventManager.o

# target to build an object file
EventManager.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/EventManager.cpp.o
.PHONY : EventManager.cpp.o

EventManager.i: EventManager.cpp.i

.PHONY : EventManager.i

# target to preprocess a source file
EventManager.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/EventManager.cpp.i
.PHONY : EventManager.cpp.i

EventManager.s: EventManager.cpp.s

.PHONY : EventManager.s

# target to generate assembly for a file
EventManager.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/EventManager.cpp.s
.PHONY : EventManager.cpp.s

ExpBar.o: ExpBar.cpp.o

.PHONY : ExpBar.o

# target to build an object file
ExpBar.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/ExpBar.cpp.o
.PHONY : ExpBar.cpp.o

ExpBar.i: ExpBar.cpp.i

.PHONY : ExpBar.i

# target to preprocess a source file
ExpBar.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/ExpBar.cpp.i
.PHONY : ExpBar.cpp.i

ExpBar.s: ExpBar.cpp.s

.PHONY : ExpBar.s

# target to generate assembly for a file
ExpBar.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/ExpBar.cpp.s
.PHONY : ExpBar.cpp.s

FilteredImage.o: FilteredImage.cpp.o

.PHONY : FilteredImage.o

# target to build an object file
FilteredImage.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/FilteredImage.cpp.o
.PHONY : FilteredImage.cpp.o

FilteredImage.i: FilteredImage.cpp.i

.PHONY : FilteredImage.i

# target to preprocess a source file
FilteredImage.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/FilteredImage.cpp.i
.PHONY : FilteredImage.cpp.i

FilteredImage.s: FilteredImage.cpp.s

.PHONY : FilteredImage.s

# target to generate assembly for a file
FilteredImage.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/FilteredImage.cpp.s
.PHONY : FilteredImage.cpp.s

Goblin.o: Goblin.cpp.o

.PHONY : Goblin.o

# target to build an object file
Goblin.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Goblin.cpp.o
.PHONY : Goblin.cpp.o

Goblin.i: Goblin.cpp.i

.PHONY : Goblin.i

# target to preprocess a source file
Goblin.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Goblin.cpp.i
.PHONY : Goblin.cpp.i

Goblin.s: Goblin.cpp.s

.PHONY : Goblin.s

# target to generate assembly for a file
Goblin.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Goblin.cpp.s
.PHONY : Goblin.cpp.s

GraphicInventory.o: GraphicInventory.cpp.o

.PHONY : GraphicInventory.o

# target to build an object file
GraphicInventory.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/GraphicInventory.cpp.o
.PHONY : GraphicInventory.cpp.o

GraphicInventory.i: GraphicInventory.cpp.i

.PHONY : GraphicInventory.i

# target to preprocess a source file
GraphicInventory.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/GraphicInventory.cpp.i
.PHONY : GraphicInventory.cpp.i

GraphicInventory.s: GraphicInventory.cpp.s

.PHONY : GraphicInventory.s

# target to generate assembly for a file
GraphicInventory.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/GraphicInventory.cpp.s
.PHONY : GraphicInventory.cpp.s

Healer.o: Healer.cpp.o

.PHONY : Healer.o

# target to build an object file
Healer.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Healer.cpp.o
.PHONY : Healer.cpp.o

Healer.i: Healer.cpp.i

.PHONY : Healer.i

# target to preprocess a source file
Healer.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Healer.cpp.i
.PHONY : Healer.cpp.i

Healer.s: Healer.cpp.s

.PHONY : Healer.s

# target to generate assembly for a file
Healer.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Healer.cpp.s
.PHONY : Healer.cpp.s

Image.o: Image.cpp.o

.PHONY : Image.o

# target to build an object file
Image.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Image.cpp.o
.PHONY : Image.cpp.o

Image.i: Image.cpp.i

.PHONY : Image.i

# target to preprocess a source file
Image.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Image.cpp.i
.PHONY : Image.cpp.i

Image.s: Image.cpp.s

.PHONY : Image.s

# target to generate assembly for a file
Image.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Image.cpp.s
.PHONY : Image.cpp.s

Item.o: Item.cpp.o

.PHONY : Item.o

# target to build an object file
Item.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Item.cpp.o
.PHONY : Item.cpp.o

Item.i: Item.cpp.i

.PHONY : Item.i

# target to preprocess a source file
Item.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Item.cpp.i
.PHONY : Item.cpp.i

Item.s: Item.cpp.s

.PHONY : Item.s

# target to generate assembly for a file
Item.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Item.cpp.s
.PHONY : Item.cpp.s

JsonError.o: JsonError.cpp.o

.PHONY : JsonError.o

# target to build an object file
JsonError.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/JsonError.cpp.o
.PHONY : JsonError.cpp.o

JsonError.i: JsonError.cpp.i

.PHONY : JsonError.i

# target to preprocess a source file
JsonError.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/JsonError.cpp.i
.PHONY : JsonError.cpp.i

JsonError.s: JsonError.cpp.s

.PHONY : JsonError.s

# target to generate assembly for a file
JsonError.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/JsonError.cpp.s
.PHONY : JsonError.cpp.s

Layout.o: Layout.cpp.o

.PHONY : Layout.o

# target to build an object file
Layout.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Layout.cpp.o
.PHONY : Layout.cpp.o

Layout.i: Layout.cpp.i

.PHONY : Layout.i

# target to preprocess a source file
Layout.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Layout.cpp.i
.PHONY : Layout.cpp.i

Layout.s: Layout.cpp.s

.PHONY : Layout.s

# target to generate assembly for a file
Layout.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Layout.cpp.s
.PHONY : Layout.cpp.s

MainMap.o: MainMap.cpp.o

.PHONY : MainMap.o

# target to build an object file
MainMap.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/MainMap.cpp.o
.PHONY : MainMap.cpp.o

MainMap.i: MainMap.cpp.i

.PHONY : MainMap.i

# target to preprocess a source file
MainMap.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/MainMap.cpp.i
.PHONY : MainMap.cpp.i

MainMap.s: MainMap.cpp.s

.PHONY : MainMap.s

# target to generate assembly for a file
MainMap.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/MainMap.cpp.s
.PHONY : MainMap.cpp.s

MainWindow.o: MainWindow.cpp.o

.PHONY : MainWindow.o

# target to build an object file
MainWindow.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/MainWindow.cpp.o
.PHONY : MainWindow.cpp.o

MainWindow.i: MainWindow.cpp.i

.PHONY : MainWindow.i

# target to preprocess a source file
MainWindow.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/MainWindow.cpp.i
.PHONY : MainWindow.cpp.i

MainWindow.s: MainWindow.cpp.s

.PHONY : MainWindow.s

# target to generate assembly for a file
MainWindow.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/MainWindow.cpp.s
.PHONY : MainWindow.cpp.s

MapImage.o: MapImage.cpp.o

.PHONY : MapImage.o

# target to build an object file
MapImage.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/MapImage.cpp.o
.PHONY : MapImage.cpp.o

MapImage.i: MapImage.cpp.i

.PHONY : MapImage.i

# target to preprocess a source file
MapImage.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/MapImage.cpp.i
.PHONY : MapImage.cpp.i

MapImage.s: MapImage.cpp.s

.PHONY : MapImage.s

# target to generate assembly for a file
MapImage.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/MapImage.cpp.s
.PHONY : MapImage.cpp.s

Merchant.o: Merchant.cpp.o

.PHONY : Merchant.o

# target to build an object file
Merchant.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Merchant.cpp.o
.PHONY : Merchant.cpp.o

Merchant.i: Merchant.cpp.i

.PHONY : Merchant.i

# target to preprocess a source file
Merchant.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Merchant.cpp.i
.PHONY : Merchant.cpp.i

Merchant.s: Merchant.cpp.s

.PHONY : Merchant.s

# target to generate assembly for a file
Merchant.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Merchant.cpp.s
.PHONY : Merchant.cpp.s

MessageQueue.o: MessageQueue.cpp.o

.PHONY : MessageQueue.o

# target to build an object file
MessageQueue.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/MessageQueue.cpp.o
.PHONY : MessageQueue.cpp.o

MessageQueue.i: MessageQueue.cpp.i

.PHONY : MessageQueue.i

# target to preprocess a source file
MessageQueue.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/MessageQueue.cpp.i
.PHONY : MessageQueue.cpp.i

MessageQueue.s: MessageQueue.cpp.s

.PHONY : MessageQueue.s

# target to generate assembly for a file
MessageQueue.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/MessageQueue.cpp.s
.PHONY : MessageQueue.cpp.s

MiniChat.o: MiniChat.cpp.o

.PHONY : MiniChat.o

# target to build an object file
MiniChat.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/MiniChat.cpp.o
.PHONY : MiniChat.cpp.o

MiniChat.i: MiniChat.cpp.i

.PHONY : MiniChat.i

# target to preprocess a source file
MiniChat.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/MiniChat.cpp.i
.PHONY : MiniChat.cpp.i

MiniChat.s: MiniChat.cpp.s

.PHONY : MiniChat.s

# target to generate assembly for a file
MiniChat.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/MiniChat.cpp.s
.PHONY : MiniChat.cpp.s

ModelController.o: ModelController.cpp.o

.PHONY : ModelController.o

# target to build an object file
ModelController.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/ModelController.cpp.o
.PHONY : ModelController.cpp.o

ModelController.i: ModelController.cpp.i

.PHONY : ModelController.i

# target to preprocess a source file
ModelController.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/ModelController.cpp.i
.PHONY : ModelController.cpp.i

ModelController.s: ModelController.cpp.s

.PHONY : ModelController.s

# target to generate assembly for a file
ModelController.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/ModelController.cpp.s
.PHONY : ModelController.cpp.s

NPC.o: NPC.cpp.o

.PHONY : NPC.o

# target to build an object file
NPC.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/NPC.cpp.o
.PHONY : NPC.cpp.o

NPC.i: NPC.cpp.i

.PHONY : NPC.i

# target to preprocess a source file
NPC.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/NPC.cpp.i
.PHONY : NPC.cpp.i

NPC.s: NPC.cpp.s

.PHONY : NPC.s

# target to generate assembly for a file
NPC.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/NPC.cpp.s
.PHONY : NPC.cpp.s

OSError.o: OSError.cpp.o

.PHONY : OSError.o

# target to build an object file
OSError.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/OSError.cpp.o
.PHONY : OSError.cpp.o

OSError.i: OSError.cpp.i

.PHONY : OSError.i

# target to preprocess a source file
OSError.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/OSError.cpp.i
.PHONY : OSError.cpp.i

OSError.s: OSError.cpp.s

.PHONY : OSError.s

# target to generate assembly for a file
OSError.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/OSError.cpp.s
.PHONY : OSError.cpp.s

Player.o: Player.cpp.o

.PHONY : Player.o

# target to build an object file
Player.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Player.cpp.o
.PHONY : Player.cpp.o

Player.i: Player.cpp.i

.PHONY : Player.i

# target to preprocess a source file
Player.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Player.cpp.i
.PHONY : Player.cpp.i

Player.s: Player.cpp.s

.PHONY : Player.s

# target to generate assembly for a file
Player.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Player.cpp.s
.PHONY : Player.cpp.s

QuitException.o: QuitException.cpp.o

.PHONY : QuitException.o

# target to build an object file
QuitException.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/QuitException.cpp.o
.PHONY : QuitException.cpp.o

QuitException.i: QuitException.cpp.i

.PHONY : QuitException.i

# target to preprocess a source file
QuitException.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/QuitException.cpp.i
.PHONY : QuitException.cpp.i

QuitException.s: QuitException.cpp.s

.PHONY : QuitException.s

# target to generate assembly for a file
QuitException.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/QuitException.cpp.s
.PHONY : QuitException.cpp.s

Receiver.o: Receiver.cpp.o

.PHONY : Receiver.o

# target to build an object file
Receiver.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Receiver.cpp.o
.PHONY : Receiver.cpp.o

Receiver.i: Receiver.cpp.i

.PHONY : Receiver.i

# target to preprocess a source file
Receiver.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Receiver.cpp.i
.PHONY : Receiver.cpp.i

Receiver.s: Receiver.cpp.s

.PHONY : Receiver.s

# target to generate assembly for a file
Receiver.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Receiver.cpp.s
.PHONY : Receiver.cpp.s

Renderer.o: Renderer.cpp.o

.PHONY : Renderer.o

# target to build an object file
Renderer.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Renderer.cpp.o
.PHONY : Renderer.cpp.o

Renderer.i: Renderer.cpp.i

.PHONY : Renderer.i

# target to preprocess a source file
Renderer.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Renderer.cpp.i
.PHONY : Renderer.cpp.i

Renderer.s: Renderer.cpp.s

.PHONY : Renderer.s

# target to generate assembly for a file
Renderer.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Renderer.cpp.s
.PHONY : Renderer.cpp.s

SDLError.o: SDLError.cpp.o

.PHONY : SDLError.o

# target to build an object file
SDLError.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/SDLError.cpp.o
.PHONY : SDLError.cpp.o

SDLError.i: SDLError.cpp.i

.PHONY : SDLError.i

# target to preprocess a source file
SDLError.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/SDLError.cpp.i
.PHONY : SDLError.cpp.i

SDLError.s: SDLError.cpp.s

.PHONY : SDLError.s

# target to generate assembly for a file
SDLError.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/SDLError.cpp.s
.PHONY : SDLError.cpp.s

Sender.o: Sender.cpp.o

.PHONY : Sender.o

# target to build an object file
Sender.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Sender.cpp.o
.PHONY : Sender.cpp.o

Sender.i: Sender.cpp.i

.PHONY : Sender.i

# target to preprocess a source file
Sender.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Sender.cpp.i
.PHONY : Sender.cpp.i

Sender.s: Sender.cpp.s

.PHONY : Sender.s

# target to generate assembly for a file
Sender.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Sender.cpp.s
.PHONY : Sender.cpp.s

Skeleton.o: Skeleton.cpp.o

.PHONY : Skeleton.o

# target to build an object file
Skeleton.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Skeleton.cpp.o
.PHONY : Skeleton.cpp.o

Skeleton.i: Skeleton.cpp.i

.PHONY : Skeleton.i

# target to preprocess a source file
Skeleton.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Skeleton.cpp.i
.PHONY : Skeleton.cpp.i

Skeleton.s: Skeleton.cpp.s

.PHONY : Skeleton.s

# target to generate assembly for a file
Skeleton.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Skeleton.cpp.s
.PHONY : Skeleton.cpp.s

Socket.o: Socket.cpp.o

.PHONY : Socket.o

# target to build an object file
Socket.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Socket.cpp.o
.PHONY : Socket.cpp.o

Socket.i: Socket.cpp.i

.PHONY : Socket.i

# target to preprocess a source file
Socket.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Socket.cpp.i
.PHONY : Socket.cpp.i

Socket.s: Socket.cpp.s

.PHONY : Socket.s

# target to generate assembly for a file
Socket.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Socket.cpp.s
.PHONY : Socket.cpp.s

SocketException.o: SocketException.cpp.o

.PHONY : SocketException.o

# target to build an object file
SocketException.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/SocketException.cpp.o
.PHONY : SocketException.cpp.o

SocketException.i: SocketException.cpp.i

.PHONY : SocketException.i

# target to preprocess a source file
SocketException.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/SocketException.cpp.i
.PHONY : SocketException.cpp.i

SocketException.s: SocketException.cpp.s

.PHONY : SocketException.s

# target to generate assembly for a file
SocketException.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/SocketException.cpp.s
.PHONY : SocketException.cpp.s

SpriteClipCreator.o: SpriteClipCreator.cpp.o

.PHONY : SpriteClipCreator.o

# target to build an object file
SpriteClipCreator.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/SpriteClipCreator.cpp.o
.PHONY : SpriteClipCreator.cpp.o

SpriteClipCreator.i: SpriteClipCreator.cpp.i

.PHONY : SpriteClipCreator.i

# target to preprocess a source file
SpriteClipCreator.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/SpriteClipCreator.cpp.i
.PHONY : SpriteClipCreator.cpp.i

SpriteClipCreator.s: SpriteClipCreator.cpp.s

.PHONY : SpriteClipCreator.s

# target to generate assembly for a file
SpriteClipCreator.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/SpriteClipCreator.cpp.s
.PHONY : SpriteClipCreator.cpp.s

Spyder.o: Spyder.cpp.o

.PHONY : Spyder.o

# target to build an object file
Spyder.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Spyder.cpp.o
.PHONY : Spyder.cpp.o

Spyder.i: Spyder.cpp.i

.PHONY : Spyder.i

# target to preprocess a source file
Spyder.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Spyder.cpp.i
.PHONY : Spyder.cpp.i

Spyder.s: Spyder.cpp.s

.PHONY : Spyder.s

# target to generate assembly for a file
Spyder.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Spyder.cpp.s
.PHONY : Spyder.cpp.s

Text.o: Text.cpp.o

.PHONY : Text.o

# target to build an object file
Text.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Text.cpp.o
.PHONY : Text.cpp.o

Text.i: Text.cpp.i

.PHONY : Text.i

# target to preprocess a source file
Text.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Text.cpp.i
.PHONY : Text.cpp.i

Text.s: Text.cpp.s

.PHONY : Text.s

# target to generate assembly for a file
Text.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Text.cpp.s
.PHONY : Text.cpp.s

Texture.o: Texture.cpp.o

.PHONY : Texture.o

# target to build an object file
Texture.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Texture.cpp.o
.PHONY : Texture.cpp.o

Texture.i: Texture.cpp.i

.PHONY : Texture.i

# target to preprocess a source file
Texture.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Texture.cpp.i
.PHONY : Texture.cpp.i

Texture.s: Texture.cpp.s

.PHONY : Texture.s

# target to generate assembly for a file
Texture.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Texture.cpp.s
.PHONY : Texture.cpp.s

Thread.o: Thread.cpp.o

.PHONY : Thread.o

# target to build an object file
Thread.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Thread.cpp.o
.PHONY : Thread.cpp.o

Thread.i: Thread.cpp.i

.PHONY : Thread.i

# target to preprocess a source file
Thread.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Thread.cpp.i
.PHONY : Thread.cpp.i

Thread.s: Thread.cpp.s

.PHONY : Thread.s

# target to generate assembly for a file
Thread.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Thread.cpp.s
.PHONY : Thread.cpp.s

Zombie.o: Zombie.cpp.o

.PHONY : Zombie.o

# target to build an object file
Zombie.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Zombie.cpp.o
.PHONY : Zombie.cpp.o

Zombie.i: Zombie.cpp.i

.PHONY : Zombie.i

# target to preprocess a source file
Zombie.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Zombie.cpp.i
.PHONY : Zombie.cpp.i

Zombie.s: Zombie.cpp.s

.PHONY : Zombie.s

# target to generate assembly for a file
Zombie.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/Zombie.cpp.s
.PHONY : Zombie.cpp.s

client.o: client.cpp.o

.PHONY : client.o

# target to build an object file
client.cpp.o:
	$(MAKE) -f CMakeFiles/prueba.dir/build.make CMakeFiles/prueba.dir/client.cpp.o
.PHONY : client.cpp.o

client.i: client.cpp.i

.PHONY : client.i

# target to preprocess a source file
client.cpp.i:
	$(MAKE) -f CMakeFiles/prueba.dir/build.make CMakeFiles/prueba.dir/client.cpp.i
.PHONY : client.cpp.i

client.s: client.cpp.s

.PHONY : client.s

# target to generate assembly for a file
client.cpp.s:
	$(MAKE) -f CMakeFiles/prueba.dir/build.make CMakeFiles/prueba.dir/client.cpp.s
.PHONY : client.cpp.s

jsoncpp.o: jsoncpp.cpp.o

.PHONY : jsoncpp.o

# target to build an object file
jsoncpp.cpp.o:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/jsoncpp.cpp.o
.PHONY : jsoncpp.cpp.o

jsoncpp.i: jsoncpp.cpp.i

.PHONY : jsoncpp.i

# target to preprocess a source file
jsoncpp.cpp.i:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/jsoncpp.cpp.i
.PHONY : jsoncpp.cpp.i

jsoncpp.s: jsoncpp.cpp.s

.PHONY : jsoncpp.s

# target to generate assembly for a file
jsoncpp.cpp.s:
	$(MAKE) -f CMakeFiles/pruebasss.dir/build.make CMakeFiles/pruebasss.dir/jsoncpp.cpp.s
.PHONY : jsoncpp.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... pruebasss"
	@echo "... prueba"
	@echo "... Banker.o"
	@echo "... Banker.i"
	@echo "... Banker.s"
	@echo "... Camera.o"
	@echo "... Camera.i"
	@echo "... Camera.s"
	@echo "... ClientConnector.o"
	@echo "... ClientConnector.i"
	@echo "... ClientConnector.s"
	@echo "... ClientController.o"
	@echo "... ClientController.i"
	@echo "... ClientController.s"
	@echo "... ClientProtocol.o"
	@echo "... ClientProtocol.i"
	@echo "... ClientProtocol.s"
	@echo "... EmptyException.o"
	@echo "... EmptyException.i"
	@echo "... EmptyException.s"
	@echo "... Entity.o"
	@echo "... Entity.i"
	@echo "... Entity.s"
	@echo "... EntityManager.o"
	@echo "... EntityManager.i"
	@echo "... EntityManager.s"
	@echo "... EventManager.o"
	@echo "... EventManager.i"
	@echo "... EventManager.s"
	@echo "... ExpBar.o"
	@echo "... ExpBar.i"
	@echo "... ExpBar.s"
	@echo "... FilteredImage.o"
	@echo "... FilteredImage.i"
	@echo "... FilteredImage.s"
	@echo "... Goblin.o"
	@echo "... Goblin.i"
	@echo "... Goblin.s"
	@echo "... GraphicInventory.o"
	@echo "... GraphicInventory.i"
	@echo "... GraphicInventory.s"
	@echo "... Healer.o"
	@echo "... Healer.i"
	@echo "... Healer.s"
	@echo "... Image.o"
	@echo "... Image.i"
	@echo "... Image.s"
	@echo "... Item.o"
	@echo "... Item.i"
	@echo "... Item.s"
	@echo "... JsonError.o"
	@echo "... JsonError.i"
	@echo "... JsonError.s"
	@echo "... Layout.o"
	@echo "... Layout.i"
	@echo "... Layout.s"
	@echo "... MainMap.o"
	@echo "... MainMap.i"
	@echo "... MainMap.s"
	@echo "... MainWindow.o"
	@echo "... MainWindow.i"
	@echo "... MainWindow.s"
	@echo "... MapImage.o"
	@echo "... MapImage.i"
	@echo "... MapImage.s"
	@echo "... Merchant.o"
	@echo "... Merchant.i"
	@echo "... Merchant.s"
	@echo "... MessageQueue.o"
	@echo "... MessageQueue.i"
	@echo "... MessageQueue.s"
	@echo "... MiniChat.o"
	@echo "... MiniChat.i"
	@echo "... MiniChat.s"
	@echo "... ModelController.o"
	@echo "... ModelController.i"
	@echo "... ModelController.s"
	@echo "... NPC.o"
	@echo "... NPC.i"
	@echo "... NPC.s"
	@echo "... OSError.o"
	@echo "... OSError.i"
	@echo "... OSError.s"
	@echo "... Player.o"
	@echo "... Player.i"
	@echo "... Player.s"
	@echo "... QuitException.o"
	@echo "... QuitException.i"
	@echo "... QuitException.s"
	@echo "... Receiver.o"
	@echo "... Receiver.i"
	@echo "... Receiver.s"
	@echo "... Renderer.o"
	@echo "... Renderer.i"
	@echo "... Renderer.s"
	@echo "... SDLError.o"
	@echo "... SDLError.i"
	@echo "... SDLError.s"
	@echo "... Sender.o"
	@echo "... Sender.i"
	@echo "... Sender.s"
	@echo "... Skeleton.o"
	@echo "... Skeleton.i"
	@echo "... Skeleton.s"
	@echo "... Socket.o"
	@echo "... Socket.i"
	@echo "... Socket.s"
	@echo "... SocketException.o"
	@echo "... SocketException.i"
	@echo "... SocketException.s"
	@echo "... SpriteClipCreator.o"
	@echo "... SpriteClipCreator.i"
	@echo "... SpriteClipCreator.s"
	@echo "... Spyder.o"
	@echo "... Spyder.i"
	@echo "... Spyder.s"
	@echo "... Text.o"
	@echo "... Text.i"
	@echo "... Text.s"
	@echo "... Texture.o"
	@echo "... Texture.i"
	@echo "... Texture.s"
	@echo "... Thread.o"
	@echo "... Thread.i"
	@echo "... Thread.s"
	@echo "... Zombie.o"
	@echo "... Zombie.i"
	@echo "... Zombie.s"
	@echo "... client.o"
	@echo "... client.i"
	@echo "... client.s"
	@echo "... jsoncpp.o"
	@echo "... jsoncpp.i"
	@echo "... jsoncpp.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

