# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/media/sf_Orga_de_compus/Facultad/Taller de Programacion I/Taller-TP-Final"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/media/sf_Orga_de_compus/Facultad/Taller de Programacion I/Taller-TP-Final"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/media/sf_Orga_de_compus/Facultad/Taller de Programacion I/Taller-TP-Final/CMakeFiles" "/media/sf_Orga_de_compus/Facultad/Taller de Programacion I/Taller-TP-Final/CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/media/sf_Orga_de_compus/Facultad/Taller de Programacion I/Taller-TP-Final/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named testgian

# Build rule for target.
testgian: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testgian
.PHONY : testgian

# fast build rule for target.
testgian/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/build
.PHONY : testgian/fast

ExpBar.o: ExpBar.cpp.o

.PHONY : ExpBar.o

# target to build an object file
ExpBar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/ExpBar.cpp.o
.PHONY : ExpBar.cpp.o

ExpBar.i: ExpBar.cpp.i

.PHONY : ExpBar.i

# target to preprocess a source file
ExpBar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/ExpBar.cpp.i
.PHONY : ExpBar.cpp.i

ExpBar.s: ExpBar.cpp.s

.PHONY : ExpBar.s

# target to generate assembly for a file
ExpBar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/ExpBar.cpp.s
.PHONY : ExpBar.cpp.s

FilteredImage.o: FilteredImage.cpp.o

.PHONY : FilteredImage.o

# target to build an object file
FilteredImage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/FilteredImage.cpp.o
.PHONY : FilteredImage.cpp.o

FilteredImage.i: FilteredImage.cpp.i

.PHONY : FilteredImage.i

# target to preprocess a source file
FilteredImage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/FilteredImage.cpp.i
.PHONY : FilteredImage.cpp.i

FilteredImage.s: FilteredImage.cpp.s

.PHONY : FilteredImage.s

# target to generate assembly for a file
FilteredImage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/FilteredImage.cpp.s
.PHONY : FilteredImage.cpp.s

GraphicInventory.o: GraphicInventory.cpp.o

.PHONY : GraphicInventory.o

# target to build an object file
GraphicInventory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/GraphicInventory.cpp.o
.PHONY : GraphicInventory.cpp.o

GraphicInventory.i: GraphicInventory.cpp.i

.PHONY : GraphicInventory.i

# target to preprocess a source file
GraphicInventory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/GraphicInventory.cpp.i
.PHONY : GraphicInventory.cpp.i

GraphicInventory.s: GraphicInventory.cpp.s

.PHONY : GraphicInventory.s

# target to generate assembly for a file
GraphicInventory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/GraphicInventory.cpp.s
.PHONY : GraphicInventory.cpp.s

Image.o: Image.cpp.o

.PHONY : Image.o

# target to build an object file
Image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/Image.cpp.o
.PHONY : Image.cpp.o

Image.i: Image.cpp.i

.PHONY : Image.i

# target to preprocess a source file
Image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/Image.cpp.i
.PHONY : Image.cpp.i

Image.s: Image.cpp.s

.PHONY : Image.s

# target to generate assembly for a file
Image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/Image.cpp.s
.PHONY : Image.cpp.s

Layout.o: Layout.cpp.o

.PHONY : Layout.o

# target to build an object file
Layout.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/Layout.cpp.o
.PHONY : Layout.cpp.o

Layout.i: Layout.cpp.i

.PHONY : Layout.i

# target to preprocess a source file
Layout.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/Layout.cpp.i
.PHONY : Layout.cpp.i

Layout.s: Layout.cpp.s

.PHONY : Layout.s

# target to generate assembly for a file
Layout.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/Layout.cpp.s
.PHONY : Layout.cpp.s

LoginScreen.o: LoginScreen.cpp.o

.PHONY : LoginScreen.o

# target to build an object file
LoginScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/LoginScreen.cpp.o
.PHONY : LoginScreen.cpp.o

LoginScreen.i: LoginScreen.cpp.i

.PHONY : LoginScreen.i

# target to preprocess a source file
LoginScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/LoginScreen.cpp.i
.PHONY : LoginScreen.cpp.i

LoginScreen.s: LoginScreen.cpp.s

.PHONY : LoginScreen.s

# target to generate assembly for a file
LoginScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/LoginScreen.cpp.s
.PHONY : LoginScreen.cpp.s

MiniChat.o: MiniChat.cpp.o

.PHONY : MiniChat.o

# target to build an object file
MiniChat.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/MiniChat.cpp.o
.PHONY : MiniChat.cpp.o

MiniChat.i: MiniChat.cpp.i

.PHONY : MiniChat.i

# target to preprocess a source file
MiniChat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/MiniChat.cpp.i
.PHONY : MiniChat.cpp.i

MiniChat.s: MiniChat.cpp.s

.PHONY : MiniChat.s

# target to generate assembly for a file
MiniChat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/MiniChat.cpp.s
.PHONY : MiniChat.cpp.s

Music.o: Music.cpp.o

.PHONY : Music.o

# target to build an object file
Music.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/Music.cpp.o
.PHONY : Music.cpp.o

Music.i: Music.cpp.i

.PHONY : Music.i

# target to preprocess a source file
Music.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/Music.cpp.i
.PHONY : Music.cpp.i

Music.s: Music.cpp.s

.PHONY : Music.s

# target to generate assembly for a file
Music.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/Music.cpp.s
.PHONY : Music.cpp.s

MusicPlayer.o: MusicPlayer.cpp.o

.PHONY : MusicPlayer.o

# target to build an object file
MusicPlayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/MusicPlayer.cpp.o
.PHONY : MusicPlayer.cpp.o

MusicPlayer.i: MusicPlayer.cpp.i

.PHONY : MusicPlayer.i

# target to preprocess a source file
MusicPlayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/MusicPlayer.cpp.i
.PHONY : MusicPlayer.cpp.i

MusicPlayer.s: MusicPlayer.cpp.s

.PHONY : MusicPlayer.s

# target to generate assembly for a file
MusicPlayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/MusicPlayer.cpp.s
.PHONY : MusicPlayer.cpp.s

SDLError.o: SDLError.cpp.o

.PHONY : SDLError.o

# target to build an object file
SDLError.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/SDLError.cpp.o
.PHONY : SDLError.cpp.o

SDLError.i: SDLError.cpp.i

.PHONY : SDLError.i

# target to preprocess a source file
SDLError.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/SDLError.cpp.i
.PHONY : SDLError.cpp.i

SDLError.s: SDLError.cpp.s

.PHONY : SDLError.s

# target to generate assembly for a file
SDLError.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/SDLError.cpp.s
.PHONY : SDLError.cpp.s

SoundEffect.o: SoundEffect.cpp.o

.PHONY : SoundEffect.o

# target to build an object file
SoundEffect.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/SoundEffect.cpp.o
.PHONY : SoundEffect.cpp.o

SoundEffect.i: SoundEffect.cpp.i

.PHONY : SoundEffect.i

# target to preprocess a source file
SoundEffect.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/SoundEffect.cpp.i
.PHONY : SoundEffect.cpp.i

SoundEffect.s: SoundEffect.cpp.s

.PHONY : SoundEffect.s

# target to generate assembly for a file
SoundEffect.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/SoundEffect.cpp.s
.PHONY : SoundEffect.cpp.s

SoundEffectPlayer.o: SoundEffectPlayer.cpp.o

.PHONY : SoundEffectPlayer.o

# target to build an object file
SoundEffectPlayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/SoundEffectPlayer.cpp.o
.PHONY : SoundEffectPlayer.cpp.o

SoundEffectPlayer.i: SoundEffectPlayer.cpp.i

.PHONY : SoundEffectPlayer.i

# target to preprocess a source file
SoundEffectPlayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/SoundEffectPlayer.cpp.i
.PHONY : SoundEffectPlayer.cpp.i

SoundEffectPlayer.s: SoundEffectPlayer.cpp.s

.PHONY : SoundEffectPlayer.s

# target to generate assembly for a file
SoundEffectPlayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/SoundEffectPlayer.cpp.s
.PHONY : SoundEffectPlayer.cpp.s

Test_gian.o: Test_gian.cpp.o

.PHONY : Test_gian.o

# target to build an object file
Test_gian.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/Test_gian.cpp.o
.PHONY : Test_gian.cpp.o

Test_gian.i: Test_gian.cpp.i

.PHONY : Test_gian.i

# target to preprocess a source file
Test_gian.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/Test_gian.cpp.i
.PHONY : Test_gian.cpp.i

Test_gian.s: Test_gian.cpp.s

.PHONY : Test_gian.s

# target to generate assembly for a file
Test_gian.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/Test_gian.cpp.s
.PHONY : Test_gian.cpp.s

Text.o: Text.cpp.o

.PHONY : Text.o

# target to build an object file
Text.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/Text.cpp.o
.PHONY : Text.cpp.o

Text.i: Text.cpp.i

.PHONY : Text.i

# target to preprocess a source file
Text.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/Text.cpp.i
.PHONY : Text.cpp.i

Text.s: Text.cpp.s

.PHONY : Text.s

# target to generate assembly for a file
Text.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/Text.cpp.s
.PHONY : Text.cpp.s

Texture.o: Texture.cpp.o

.PHONY : Texture.o

# target to build an object file
Texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/Texture.cpp.o
.PHONY : Texture.cpp.o

Texture.i: Texture.cpp.i

.PHONY : Texture.i

# target to preprocess a source file
Texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/Texture.cpp.i
.PHONY : Texture.cpp.i

Texture.s: Texture.cpp.s

.PHONY : Texture.s

# target to generate assembly for a file
Texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/Texture.cpp.s
.PHONY : Texture.cpp.s

prueba_de_sonido.o: prueba_de_sonido.cpp.o

.PHONY : prueba_de_sonido.o

# target to build an object file
prueba_de_sonido.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/prueba_de_sonido.cpp.o
.PHONY : prueba_de_sonido.cpp.o

prueba_de_sonido.i: prueba_de_sonido.cpp.i

.PHONY : prueba_de_sonido.i

# target to preprocess a source file
prueba_de_sonido.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/prueba_de_sonido.cpp.i
.PHONY : prueba_de_sonido.cpp.i

prueba_de_sonido.s: prueba_de_sonido.cpp.s

.PHONY : prueba_de_sonido.s

# target to generate assembly for a file
prueba_de_sonido.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgian.dir/build.make CMakeFiles/testgian.dir/prueba_de_sonido.cpp.s
.PHONY : prueba_de_sonido.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... testgian"
	@echo "... ExpBar.o"
	@echo "... ExpBar.i"
	@echo "... ExpBar.s"
	@echo "... FilteredImage.o"
	@echo "... FilteredImage.i"
	@echo "... FilteredImage.s"
	@echo "... GraphicInventory.o"
	@echo "... GraphicInventory.i"
	@echo "... GraphicInventory.s"
	@echo "... Image.o"
	@echo "... Image.i"
	@echo "... Image.s"
	@echo "... Layout.o"
	@echo "... Layout.i"
	@echo "... Layout.s"
	@echo "... LoginScreen.o"
	@echo "... LoginScreen.i"
	@echo "... LoginScreen.s"
	@echo "... MiniChat.o"
	@echo "... MiniChat.i"
	@echo "... MiniChat.s"
	@echo "... Music.o"
	@echo "... Music.i"
	@echo "... Music.s"
	@echo "... MusicPlayer.o"
	@echo "... MusicPlayer.i"
	@echo "... MusicPlayer.s"
	@echo "... SDLError.o"
	@echo "... SDLError.i"
	@echo "... SDLError.s"
	@echo "... SoundEffect.o"
	@echo "... SoundEffect.i"
	@echo "... SoundEffect.s"
	@echo "... SoundEffectPlayer.o"
	@echo "... SoundEffectPlayer.i"
	@echo "... SoundEffectPlayer.s"
	@echo "... Test_gian.o"
	@echo "... Test_gian.i"
	@echo "... Test_gian.s"
	@echo "... Text.o"
	@echo "... Text.i"
	@echo "... Text.s"
	@echo "... Texture.o"
	@echo "... Texture.i"
	@echo "... Texture.s"
	@echo "... prueba_de_sonido.o"
	@echo "... prueba_de_sonido.i"
	@echo "... prueba_de_sonido.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

