# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/guidob/Escritorio/Taller de Programación 1/Argentum/Taller-TP-Final"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/guidob/Escritorio/Taller de Programación 1/Argentum/Taller-TP-Final"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/guidob/Escritorio/Taller de Programación 1/Argentum/Taller-TP-Final/CMakeFiles" "/home/guidob/Escritorio/Taller de Programación 1/Argentum/Taller-TP-Final/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/guidob/Escritorio/Taller de Programación 1/Argentum/Taller-TP-Final/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named clientLib

# Build rule for target.
clientLib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clientLib
.PHONY : clientLib

# fast build rule for target.
clientLib/fast:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/build
.PHONY : clientLib/fast

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

client_src/Banker.o: client_src/Banker.cpp.o

.PHONY : client_src/Banker.o

# target to build an object file
client_src/Banker.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Banker.cpp.o
.PHONY : client_src/Banker.cpp.o

client_src/Banker.i: client_src/Banker.cpp.i

.PHONY : client_src/Banker.i

# target to preprocess a source file
client_src/Banker.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Banker.cpp.i
.PHONY : client_src/Banker.cpp.i

client_src/Banker.s: client_src/Banker.cpp.s

.PHONY : client_src/Banker.s

# target to generate assembly for a file
client_src/Banker.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Banker.cpp.s
.PHONY : client_src/Banker.cpp.s

client_src/BlockingMsgQueue.o: client_src/BlockingMsgQueue.cpp.o

.PHONY : client_src/BlockingMsgQueue.o

# target to build an object file
client_src/BlockingMsgQueue.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/BlockingMsgQueue.cpp.o
.PHONY : client_src/BlockingMsgQueue.cpp.o

client_src/BlockingMsgQueue.i: client_src/BlockingMsgQueue.cpp.i

.PHONY : client_src/BlockingMsgQueue.i

# target to preprocess a source file
client_src/BlockingMsgQueue.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/BlockingMsgQueue.cpp.i
.PHONY : client_src/BlockingMsgQueue.cpp.i

client_src/BlockingMsgQueue.s: client_src/BlockingMsgQueue.cpp.s

.PHONY : client_src/BlockingMsgQueue.s

# target to generate assembly for a file
client_src/BlockingMsgQueue.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/BlockingMsgQueue.cpp.s
.PHONY : client_src/BlockingMsgQueue.cpp.s

client_src/Camera.o: client_src/Camera.cpp.o

.PHONY : client_src/Camera.o

# target to build an object file
client_src/Camera.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Camera.cpp.o
.PHONY : client_src/Camera.cpp.o

client_src/Camera.i: client_src/Camera.cpp.i

.PHONY : client_src/Camera.i

# target to preprocess a source file
client_src/Camera.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Camera.cpp.i
.PHONY : client_src/Camera.cpp.i

client_src/Camera.s: client_src/Camera.cpp.s

.PHONY : client_src/Camera.s

# target to generate assembly for a file
client_src/Camera.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Camera.cpp.s
.PHONY : client_src/Camera.cpp.s

client_src/ClientConnector.o: client_src/ClientConnector.cpp.o

.PHONY : client_src/ClientConnector.o

# target to build an object file
client_src/ClientConnector.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/ClientConnector.cpp.o
.PHONY : client_src/ClientConnector.cpp.o

client_src/ClientConnector.i: client_src/ClientConnector.cpp.i

.PHONY : client_src/ClientConnector.i

# target to preprocess a source file
client_src/ClientConnector.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/ClientConnector.cpp.i
.PHONY : client_src/ClientConnector.cpp.i

client_src/ClientConnector.s: client_src/ClientConnector.cpp.s

.PHONY : client_src/ClientConnector.s

# target to generate assembly for a file
client_src/ClientConnector.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/ClientConnector.cpp.s
.PHONY : client_src/ClientConnector.cpp.s

client_src/ClientController.o: client_src/ClientController.cpp.o

.PHONY : client_src/ClientController.o

# target to build an object file
client_src/ClientController.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/ClientController.cpp.o
.PHONY : client_src/ClientController.cpp.o

client_src/ClientController.i: client_src/ClientController.cpp.i

.PHONY : client_src/ClientController.i

# target to preprocess a source file
client_src/ClientController.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/ClientController.cpp.i
.PHONY : client_src/ClientController.cpp.i

client_src/ClientController.s: client_src/ClientController.cpp.s

.PHONY : client_src/ClientController.s

# target to generate assembly for a file
client_src/ClientController.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/ClientController.cpp.s
.PHONY : client_src/ClientController.cpp.s

client_src/ClientProtocol.o: client_src/ClientProtocol.cpp.o

.PHONY : client_src/ClientProtocol.o

# target to build an object file
client_src/ClientProtocol.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/ClientProtocol.cpp.o
.PHONY : client_src/ClientProtocol.cpp.o

client_src/ClientProtocol.i: client_src/ClientProtocol.cpp.i

.PHONY : client_src/ClientProtocol.i

# target to preprocess a source file
client_src/ClientProtocol.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/ClientProtocol.cpp.i
.PHONY : client_src/ClientProtocol.cpp.i

client_src/ClientProtocol.s: client_src/ClientProtocol.cpp.s

.PHONY : client_src/ClientProtocol.s

# target to generate assembly for a file
client_src/ClientProtocol.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/ClientProtocol.cpp.s
.PHONY : client_src/ClientProtocol.cpp.s

client_src/Entity.o: client_src/Entity.cpp.o

.PHONY : client_src/Entity.o

# target to build an object file
client_src/Entity.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Entity.cpp.o
.PHONY : client_src/Entity.cpp.o

client_src/Entity.i: client_src/Entity.cpp.i

.PHONY : client_src/Entity.i

# target to preprocess a source file
client_src/Entity.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Entity.cpp.i
.PHONY : client_src/Entity.cpp.i

client_src/Entity.s: client_src/Entity.cpp.s

.PHONY : client_src/Entity.s

# target to generate assembly for a file
client_src/Entity.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Entity.cpp.s
.PHONY : client_src/Entity.cpp.s

client_src/EntityManager.o: client_src/EntityManager.cpp.o

.PHONY : client_src/EntityManager.o

# target to build an object file
client_src/EntityManager.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/EntityManager.cpp.o
.PHONY : client_src/EntityManager.cpp.o

client_src/EntityManager.i: client_src/EntityManager.cpp.i

.PHONY : client_src/EntityManager.i

# target to preprocess a source file
client_src/EntityManager.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/EntityManager.cpp.i
.PHONY : client_src/EntityManager.cpp.i

client_src/EntityManager.s: client_src/EntityManager.cpp.s

.PHONY : client_src/EntityManager.s

# target to generate assembly for a file
client_src/EntityManager.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/EntityManager.cpp.s
.PHONY : client_src/EntityManager.cpp.s

client_src/Equippable.o: client_src/Equippable.cpp.o

.PHONY : client_src/Equippable.o

# target to build an object file
client_src/Equippable.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Equippable.cpp.o
.PHONY : client_src/Equippable.cpp.o

client_src/Equippable.i: client_src/Equippable.cpp.i

.PHONY : client_src/Equippable.i

# target to preprocess a source file
client_src/Equippable.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Equippable.cpp.i
.PHONY : client_src/Equippable.cpp.i

client_src/Equippable.s: client_src/Equippable.cpp.s

.PHONY : client_src/Equippable.s

# target to generate assembly for a file
client_src/Equippable.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Equippable.cpp.s
.PHONY : client_src/Equippable.cpp.s

client_src/EventManager.o: client_src/EventManager.cpp.o

.PHONY : client_src/EventManager.o

# target to build an object file
client_src/EventManager.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/EventManager.cpp.o
.PHONY : client_src/EventManager.cpp.o

client_src/EventManager.i: client_src/EventManager.cpp.i

.PHONY : client_src/EventManager.i

# target to preprocess a source file
client_src/EventManager.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/EventManager.cpp.i
.PHONY : client_src/EventManager.cpp.i

client_src/EventManager.s: client_src/EventManager.cpp.s

.PHONY : client_src/EventManager.s

# target to generate assembly for a file
client_src/EventManager.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/EventManager.cpp.s
.PHONY : client_src/EventManager.cpp.s

client_src/ExpBar.o: client_src/ExpBar.cpp.o

.PHONY : client_src/ExpBar.o

# target to build an object file
client_src/ExpBar.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/ExpBar.cpp.o
.PHONY : client_src/ExpBar.cpp.o

client_src/ExpBar.i: client_src/ExpBar.cpp.i

.PHONY : client_src/ExpBar.i

# target to preprocess a source file
client_src/ExpBar.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/ExpBar.cpp.i
.PHONY : client_src/ExpBar.cpp.i

client_src/ExpBar.s: client_src/ExpBar.cpp.s

.PHONY : client_src/ExpBar.s

# target to generate assembly for a file
client_src/ExpBar.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/ExpBar.cpp.s
.PHONY : client_src/ExpBar.cpp.s

client_src/FilteredImage.o: client_src/FilteredImage.cpp.o

.PHONY : client_src/FilteredImage.o

# target to build an object file
client_src/FilteredImage.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/FilteredImage.cpp.o
.PHONY : client_src/FilteredImage.cpp.o

client_src/FilteredImage.i: client_src/FilteredImage.cpp.i

.PHONY : client_src/FilteredImage.i

# target to preprocess a source file
client_src/FilteredImage.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/FilteredImage.cpp.i
.PHONY : client_src/FilteredImage.cpp.i

client_src/FilteredImage.s: client_src/FilteredImage.cpp.s

.PHONY : client_src/FilteredImage.s

# target to generate assembly for a file
client_src/FilteredImage.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/FilteredImage.cpp.s
.PHONY : client_src/FilteredImage.cpp.s

client_src/Goblin.o: client_src/Goblin.cpp.o

.PHONY : client_src/Goblin.o

# target to build an object file
client_src/Goblin.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Goblin.cpp.o
.PHONY : client_src/Goblin.cpp.o

client_src/Goblin.i: client_src/Goblin.cpp.i

.PHONY : client_src/Goblin.i

# target to preprocess a source file
client_src/Goblin.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Goblin.cpp.i
.PHONY : client_src/Goblin.cpp.i

client_src/Goblin.s: client_src/Goblin.cpp.s

.PHONY : client_src/Goblin.s

# target to generate assembly for a file
client_src/Goblin.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Goblin.cpp.s
.PHONY : client_src/Goblin.cpp.s

client_src/GraphicInventory.o: client_src/GraphicInventory.cpp.o

.PHONY : client_src/GraphicInventory.o

# target to build an object file
client_src/GraphicInventory.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/GraphicInventory.cpp.o
.PHONY : client_src/GraphicInventory.cpp.o

client_src/GraphicInventory.i: client_src/GraphicInventory.cpp.i

.PHONY : client_src/GraphicInventory.i

# target to preprocess a source file
client_src/GraphicInventory.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/GraphicInventory.cpp.i
.PHONY : client_src/GraphicInventory.cpp.i

client_src/GraphicInventory.s: client_src/GraphicInventory.cpp.s

.PHONY : client_src/GraphicInventory.s

# target to generate assembly for a file
client_src/GraphicInventory.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/GraphicInventory.cpp.s
.PHONY : client_src/GraphicInventory.cpp.s

client_src/Healer.o: client_src/Healer.cpp.o

.PHONY : client_src/Healer.o

# target to build an object file
client_src/Healer.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Healer.cpp.o
.PHONY : client_src/Healer.cpp.o

client_src/Healer.i: client_src/Healer.cpp.i

.PHONY : client_src/Healer.i

# target to preprocess a source file
client_src/Healer.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Healer.cpp.i
.PHONY : client_src/Healer.cpp.i

client_src/Healer.s: client_src/Healer.cpp.s

.PHONY : client_src/Healer.s

# target to generate assembly for a file
client_src/Healer.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Healer.cpp.s
.PHONY : client_src/Healer.cpp.s

client_src/Image.o: client_src/Image.cpp.o

.PHONY : client_src/Image.o

# target to build an object file
client_src/Image.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Image.cpp.o
.PHONY : client_src/Image.cpp.o

client_src/Image.i: client_src/Image.cpp.i

.PHONY : client_src/Image.i

# target to preprocess a source file
client_src/Image.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Image.cpp.i
.PHONY : client_src/Image.cpp.i

client_src/Image.s: client_src/Image.cpp.s

.PHONY : client_src/Image.s

# target to generate assembly for a file
client_src/Image.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Image.cpp.s
.PHONY : client_src/Image.cpp.s

client_src/Item.o: client_src/Item.cpp.o

.PHONY : client_src/Item.o

# target to build an object file
client_src/Item.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Item.cpp.o
.PHONY : client_src/Item.cpp.o

client_src/Item.i: client_src/Item.cpp.i

.PHONY : client_src/Item.i

# target to preprocess a source file
client_src/Item.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Item.cpp.i
.PHONY : client_src/Item.cpp.i

client_src/Item.s: client_src/Item.cpp.s

.PHONY : client_src/Item.s

# target to generate assembly for a file
client_src/Item.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Item.cpp.s
.PHONY : client_src/Item.cpp.s

client_src/Layout.o: client_src/Layout.cpp.o

.PHONY : client_src/Layout.o

# target to build an object file
client_src/Layout.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Layout.cpp.o
.PHONY : client_src/Layout.cpp.o

client_src/Layout.i: client_src/Layout.cpp.i

.PHONY : client_src/Layout.i

# target to preprocess a source file
client_src/Layout.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Layout.cpp.i
.PHONY : client_src/Layout.cpp.i

client_src/Layout.s: client_src/Layout.cpp.s

.PHONY : client_src/Layout.s

# target to generate assembly for a file
client_src/Layout.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Layout.cpp.s
.PHONY : client_src/Layout.cpp.s

client_src/LayoutManager.o: client_src/LayoutManager.cpp.o

.PHONY : client_src/LayoutManager.o

# target to build an object file
client_src/LayoutManager.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/LayoutManager.cpp.o
.PHONY : client_src/LayoutManager.cpp.o

client_src/LayoutManager.i: client_src/LayoutManager.cpp.i

.PHONY : client_src/LayoutManager.i

# target to preprocess a source file
client_src/LayoutManager.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/LayoutManager.cpp.i
.PHONY : client_src/LayoutManager.cpp.i

client_src/LayoutManager.s: client_src/LayoutManager.cpp.s

.PHONY : client_src/LayoutManager.s

# target to generate assembly for a file
client_src/LayoutManager.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/LayoutManager.cpp.s
.PHONY : client_src/LayoutManager.cpp.s

client_src/LoginManager.o: client_src/LoginManager.cpp.o

.PHONY : client_src/LoginManager.o

# target to build an object file
client_src/LoginManager.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/LoginManager.cpp.o
.PHONY : client_src/LoginManager.cpp.o

client_src/LoginManager.i: client_src/LoginManager.cpp.i

.PHONY : client_src/LoginManager.i

# target to preprocess a source file
client_src/LoginManager.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/LoginManager.cpp.i
.PHONY : client_src/LoginManager.cpp.i

client_src/LoginManager.s: client_src/LoginManager.cpp.s

.PHONY : client_src/LoginManager.s

# target to generate assembly for a file
client_src/LoginManager.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/LoginManager.cpp.s
.PHONY : client_src/LoginManager.cpp.s

client_src/LoginScreen.o: client_src/LoginScreen.cpp.o

.PHONY : client_src/LoginScreen.o

# target to build an object file
client_src/LoginScreen.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/LoginScreen.cpp.o
.PHONY : client_src/LoginScreen.cpp.o

client_src/LoginScreen.i: client_src/LoginScreen.cpp.i

.PHONY : client_src/LoginScreen.i

# target to preprocess a source file
client_src/LoginScreen.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/LoginScreen.cpp.i
.PHONY : client_src/LoginScreen.cpp.i

client_src/LoginScreen.s: client_src/LoginScreen.cpp.s

.PHONY : client_src/LoginScreen.s

# target to generate assembly for a file
client_src/LoginScreen.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/LoginScreen.cpp.s
.PHONY : client_src/LoginScreen.cpp.s

client_src/MainMap.o: client_src/MainMap.cpp.o

.PHONY : client_src/MainMap.o

# target to build an object file
client_src/MainMap.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/MainMap.cpp.o
.PHONY : client_src/MainMap.cpp.o

client_src/MainMap.i: client_src/MainMap.cpp.i

.PHONY : client_src/MainMap.i

# target to preprocess a source file
client_src/MainMap.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/MainMap.cpp.i
.PHONY : client_src/MainMap.cpp.i

client_src/MainMap.s: client_src/MainMap.cpp.s

.PHONY : client_src/MainMap.s

# target to generate assembly for a file
client_src/MainMap.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/MainMap.cpp.s
.PHONY : client_src/MainMap.cpp.s

client_src/MainWindow.o: client_src/MainWindow.cpp.o

.PHONY : client_src/MainWindow.o

# target to build an object file
client_src/MainWindow.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/MainWindow.cpp.o
.PHONY : client_src/MainWindow.cpp.o

client_src/MainWindow.i: client_src/MainWindow.cpp.i

.PHONY : client_src/MainWindow.i

# target to preprocess a source file
client_src/MainWindow.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/MainWindow.cpp.i
.PHONY : client_src/MainWindow.cpp.i

client_src/MainWindow.s: client_src/MainWindow.cpp.s

.PHONY : client_src/MainWindow.s

# target to generate assembly for a file
client_src/MainWindow.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/MainWindow.cpp.s
.PHONY : client_src/MainWindow.cpp.s

client_src/MapImage.o: client_src/MapImage.cpp.o

.PHONY : client_src/MapImage.o

# target to build an object file
client_src/MapImage.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/MapImage.cpp.o
.PHONY : client_src/MapImage.cpp.o

client_src/MapImage.i: client_src/MapImage.cpp.i

.PHONY : client_src/MapImage.i

# target to preprocess a source file
client_src/MapImage.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/MapImage.cpp.i
.PHONY : client_src/MapImage.cpp.i

client_src/MapImage.s: client_src/MapImage.cpp.s

.PHONY : client_src/MapImage.s

# target to generate assembly for a file
client_src/MapImage.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/MapImage.cpp.s
.PHONY : client_src/MapImage.cpp.s

client_src/Merchant.o: client_src/Merchant.cpp.o

.PHONY : client_src/Merchant.o

# target to build an object file
client_src/Merchant.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Merchant.cpp.o
.PHONY : client_src/Merchant.cpp.o

client_src/Merchant.i: client_src/Merchant.cpp.i

.PHONY : client_src/Merchant.i

# target to preprocess a source file
client_src/Merchant.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Merchant.cpp.i
.PHONY : client_src/Merchant.cpp.i

client_src/Merchant.s: client_src/Merchant.cpp.s

.PHONY : client_src/Merchant.s

# target to generate assembly for a file
client_src/Merchant.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Merchant.cpp.s
.PHONY : client_src/Merchant.cpp.s

client_src/MiniChat.o: client_src/MiniChat.cpp.o

.PHONY : client_src/MiniChat.o

# target to build an object file
client_src/MiniChat.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/MiniChat.cpp.o
.PHONY : client_src/MiniChat.cpp.o

client_src/MiniChat.i: client_src/MiniChat.cpp.i

.PHONY : client_src/MiniChat.i

# target to preprocess a source file
client_src/MiniChat.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/MiniChat.cpp.i
.PHONY : client_src/MiniChat.cpp.i

client_src/MiniChat.s: client_src/MiniChat.cpp.s

.PHONY : client_src/MiniChat.s

# target to generate assembly for a file
client_src/MiniChat.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/MiniChat.cpp.s
.PHONY : client_src/MiniChat.cpp.s

client_src/ModelController.o: client_src/ModelController.cpp.o

.PHONY : client_src/ModelController.o

# target to build an object file
client_src/ModelController.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/ModelController.cpp.o
.PHONY : client_src/ModelController.cpp.o

client_src/ModelController.i: client_src/ModelController.cpp.i

.PHONY : client_src/ModelController.i

# target to preprocess a source file
client_src/ModelController.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/ModelController.cpp.i
.PHONY : client_src/ModelController.cpp.i

client_src/ModelController.s: client_src/ModelController.cpp.s

.PHONY : client_src/ModelController.s

# target to generate assembly for a file
client_src/ModelController.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/ModelController.cpp.s
.PHONY : client_src/ModelController.cpp.s

client_src/NPC.o: client_src/NPC.cpp.o

.PHONY : client_src/NPC.o

# target to build an object file
client_src/NPC.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/NPC.cpp.o
.PHONY : client_src/NPC.cpp.o

client_src/NPC.i: client_src/NPC.cpp.i

.PHONY : client_src/NPC.i

# target to preprocess a source file
client_src/NPC.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/NPC.cpp.i
.PHONY : client_src/NPC.cpp.i

client_src/NPC.s: client_src/NPC.cpp.s

.PHONY : client_src/NPC.s

# target to generate assembly for a file
client_src/NPC.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/NPC.cpp.s
.PHONY : client_src/NPC.cpp.s

client_src/OSError.o: client_src/OSError.cpp.o

.PHONY : client_src/OSError.o

# target to build an object file
client_src/OSError.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/OSError.cpp.o
.PHONY : client_src/OSError.cpp.o

client_src/OSError.i: client_src/OSError.cpp.i

.PHONY : client_src/OSError.i

# target to preprocess a source file
client_src/OSError.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/OSError.cpp.i
.PHONY : client_src/OSError.cpp.i

client_src/OSError.s: client_src/OSError.cpp.s

.PHONY : client_src/OSError.s

# target to generate assembly for a file
client_src/OSError.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/OSError.cpp.s
.PHONY : client_src/OSError.cpp.s

client_src/Player.o: client_src/Player.cpp.o

.PHONY : client_src/Player.o

# target to build an object file
client_src/Player.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Player.cpp.o
.PHONY : client_src/Player.cpp.o

client_src/Player.i: client_src/Player.cpp.i

.PHONY : client_src/Player.i

# target to preprocess a source file
client_src/Player.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Player.cpp.i
.PHONY : client_src/Player.cpp.i

client_src/Player.s: client_src/Player.cpp.s

.PHONY : client_src/Player.s

# target to generate assembly for a file
client_src/Player.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Player.cpp.s
.PHONY : client_src/Player.cpp.s

client_src/ProtMsgQueue.o: client_src/ProtMsgQueue.cpp.o

.PHONY : client_src/ProtMsgQueue.o

# target to build an object file
client_src/ProtMsgQueue.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/ProtMsgQueue.cpp.o
.PHONY : client_src/ProtMsgQueue.cpp.o

client_src/ProtMsgQueue.i: client_src/ProtMsgQueue.cpp.i

.PHONY : client_src/ProtMsgQueue.i

# target to preprocess a source file
client_src/ProtMsgQueue.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/ProtMsgQueue.cpp.i
.PHONY : client_src/ProtMsgQueue.cpp.i

client_src/ProtMsgQueue.s: client_src/ProtMsgQueue.cpp.s

.PHONY : client_src/ProtMsgQueue.s

# target to generate assembly for a file
client_src/ProtMsgQueue.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/ProtMsgQueue.cpp.s
.PHONY : client_src/ProtMsgQueue.cpp.s

client_src/QueueClosedException.o: client_src/QueueClosedException.cpp.o

.PHONY : client_src/QueueClosedException.o

# target to build an object file
client_src/QueueClosedException.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/QueueClosedException.cpp.o
.PHONY : client_src/QueueClosedException.cpp.o

client_src/QueueClosedException.i: client_src/QueueClosedException.cpp.i

.PHONY : client_src/QueueClosedException.i

# target to preprocess a source file
client_src/QueueClosedException.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/QueueClosedException.cpp.i
.PHONY : client_src/QueueClosedException.cpp.i

client_src/QueueClosedException.s: client_src/QueueClosedException.cpp.s

.PHONY : client_src/QueueClosedException.s

# target to generate assembly for a file
client_src/QueueClosedException.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/QueueClosedException.cpp.s
.PHONY : client_src/QueueClosedException.cpp.s

client_src/QuitException.o: client_src/QuitException.cpp.o

.PHONY : client_src/QuitException.o

# target to build an object file
client_src/QuitException.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/QuitException.cpp.o
.PHONY : client_src/QuitException.cpp.o

client_src/QuitException.i: client_src/QuitException.cpp.i

.PHONY : client_src/QuitException.i

# target to preprocess a source file
client_src/QuitException.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/QuitException.cpp.i
.PHONY : client_src/QuitException.cpp.i

client_src/QuitException.s: client_src/QuitException.cpp.s

.PHONY : client_src/QuitException.s

# target to generate assembly for a file
client_src/QuitException.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/QuitException.cpp.s
.PHONY : client_src/QuitException.cpp.s

client_src/Receiver.o: client_src/Receiver.cpp.o

.PHONY : client_src/Receiver.o

# target to build an object file
client_src/Receiver.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Receiver.cpp.o
.PHONY : client_src/Receiver.cpp.o

client_src/Receiver.i: client_src/Receiver.cpp.i

.PHONY : client_src/Receiver.i

# target to preprocess a source file
client_src/Receiver.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Receiver.cpp.i
.PHONY : client_src/Receiver.cpp.i

client_src/Receiver.s: client_src/Receiver.cpp.s

.PHONY : client_src/Receiver.s

# target to generate assembly for a file
client_src/Receiver.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Receiver.cpp.s
.PHONY : client_src/Receiver.cpp.s

client_src/Renderer.o: client_src/Renderer.cpp.o

.PHONY : client_src/Renderer.o

# target to build an object file
client_src/Renderer.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Renderer.cpp.o
.PHONY : client_src/Renderer.cpp.o

client_src/Renderer.i: client_src/Renderer.cpp.i

.PHONY : client_src/Renderer.i

# target to preprocess a source file
client_src/Renderer.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Renderer.cpp.i
.PHONY : client_src/Renderer.cpp.i

client_src/Renderer.s: client_src/Renderer.cpp.s

.PHONY : client_src/Renderer.s

# target to generate assembly for a file
client_src/Renderer.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Renderer.cpp.s
.PHONY : client_src/Renderer.cpp.s

client_src/SDLError.o: client_src/SDLError.cpp.o

.PHONY : client_src/SDLError.o

# target to build an object file
client_src/SDLError.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/SDLError.cpp.o
.PHONY : client_src/SDLError.cpp.o

client_src/SDLError.i: client_src/SDLError.cpp.i

.PHONY : client_src/SDLError.i

# target to preprocess a source file
client_src/SDLError.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/SDLError.cpp.i
.PHONY : client_src/SDLError.cpp.i

client_src/SDLError.s: client_src/SDLError.cpp.s

.PHONY : client_src/SDLError.s

# target to generate assembly for a file
client_src/SDLError.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/SDLError.cpp.s
.PHONY : client_src/SDLError.cpp.s

client_src/Sender.o: client_src/Sender.cpp.o

.PHONY : client_src/Sender.o

# target to build an object file
client_src/Sender.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Sender.cpp.o
.PHONY : client_src/Sender.cpp.o

client_src/Sender.i: client_src/Sender.cpp.i

.PHONY : client_src/Sender.i

# target to preprocess a source file
client_src/Sender.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Sender.cpp.i
.PHONY : client_src/Sender.cpp.i

client_src/Sender.s: client_src/Sender.cpp.s

.PHONY : client_src/Sender.s

# target to generate assembly for a file
client_src/Sender.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Sender.cpp.s
.PHONY : client_src/Sender.cpp.s

client_src/Skeleton.o: client_src/Skeleton.cpp.o

.PHONY : client_src/Skeleton.o

# target to build an object file
client_src/Skeleton.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Skeleton.cpp.o
.PHONY : client_src/Skeleton.cpp.o

client_src/Skeleton.i: client_src/Skeleton.cpp.i

.PHONY : client_src/Skeleton.i

# target to preprocess a source file
client_src/Skeleton.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Skeleton.cpp.i
.PHONY : client_src/Skeleton.cpp.i

client_src/Skeleton.s: client_src/Skeleton.cpp.s

.PHONY : client_src/Skeleton.s

# target to generate assembly for a file
client_src/Skeleton.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Skeleton.cpp.s
.PHONY : client_src/Skeleton.cpp.s

client_src/Socket.o: client_src/Socket.cpp.o

.PHONY : client_src/Socket.o

# target to build an object file
client_src/Socket.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Socket.cpp.o
.PHONY : client_src/Socket.cpp.o

client_src/Socket.i: client_src/Socket.cpp.i

.PHONY : client_src/Socket.i

# target to preprocess a source file
client_src/Socket.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Socket.cpp.i
.PHONY : client_src/Socket.cpp.i

client_src/Socket.s: client_src/Socket.cpp.s

.PHONY : client_src/Socket.s

# target to generate assembly for a file
client_src/Socket.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Socket.cpp.s
.PHONY : client_src/Socket.cpp.s

client_src/SocketException.o: client_src/SocketException.cpp.o

.PHONY : client_src/SocketException.o

# target to build an object file
client_src/SocketException.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/SocketException.cpp.o
.PHONY : client_src/SocketException.cpp.o

client_src/SocketException.i: client_src/SocketException.cpp.i

.PHONY : client_src/SocketException.i

# target to preprocess a source file
client_src/SocketException.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/SocketException.cpp.i
.PHONY : client_src/SocketException.cpp.i

client_src/SocketException.s: client_src/SocketException.cpp.s

.PHONY : client_src/SocketException.s

# target to generate assembly for a file
client_src/SocketException.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/SocketException.cpp.s
.PHONY : client_src/SocketException.cpp.s

client_src/SpriteClipCreator.o: client_src/SpriteClipCreator.cpp.o

.PHONY : client_src/SpriteClipCreator.o

# target to build an object file
client_src/SpriteClipCreator.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/SpriteClipCreator.cpp.o
.PHONY : client_src/SpriteClipCreator.cpp.o

client_src/SpriteClipCreator.i: client_src/SpriteClipCreator.cpp.i

.PHONY : client_src/SpriteClipCreator.i

# target to preprocess a source file
client_src/SpriteClipCreator.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/SpriteClipCreator.cpp.i
.PHONY : client_src/SpriteClipCreator.cpp.i

client_src/SpriteClipCreator.s: client_src/SpriteClipCreator.cpp.s

.PHONY : client_src/SpriteClipCreator.s

# target to generate assembly for a file
client_src/SpriteClipCreator.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/SpriteClipCreator.cpp.s
.PHONY : client_src/SpriteClipCreator.cpp.s

client_src/Spyder.o: client_src/Spyder.cpp.o

.PHONY : client_src/Spyder.o

# target to build an object file
client_src/Spyder.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Spyder.cpp.o
.PHONY : client_src/Spyder.cpp.o

client_src/Spyder.i: client_src/Spyder.cpp.i

.PHONY : client_src/Spyder.i

# target to preprocess a source file
client_src/Spyder.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Spyder.cpp.i
.PHONY : client_src/Spyder.cpp.i

client_src/Spyder.s: client_src/Spyder.cpp.s

.PHONY : client_src/Spyder.s

# target to generate assembly for a file
client_src/Spyder.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Spyder.cpp.s
.PHONY : client_src/Spyder.cpp.s

client_src/Text.o: client_src/Text.cpp.o

.PHONY : client_src/Text.o

# target to build an object file
client_src/Text.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Text.cpp.o
.PHONY : client_src/Text.cpp.o

client_src/Text.i: client_src/Text.cpp.i

.PHONY : client_src/Text.i

# target to preprocess a source file
client_src/Text.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Text.cpp.i
.PHONY : client_src/Text.cpp.i

client_src/Text.s: client_src/Text.cpp.s

.PHONY : client_src/Text.s

# target to generate assembly for a file
client_src/Text.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Text.cpp.s
.PHONY : client_src/Text.cpp.s

client_src/Texture.o: client_src/Texture.cpp.o

.PHONY : client_src/Texture.o

# target to build an object file
client_src/Texture.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Texture.cpp.o
.PHONY : client_src/Texture.cpp.o

client_src/Texture.i: client_src/Texture.cpp.i

.PHONY : client_src/Texture.i

# target to preprocess a source file
client_src/Texture.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Texture.cpp.i
.PHONY : client_src/Texture.cpp.i

client_src/Texture.s: client_src/Texture.cpp.s

.PHONY : client_src/Texture.s

# target to generate assembly for a file
client_src/Texture.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Texture.cpp.s
.PHONY : client_src/Texture.cpp.s

client_src/Thread.o: client_src/Thread.cpp.o

.PHONY : client_src/Thread.o

# target to build an object file
client_src/Thread.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Thread.cpp.o
.PHONY : client_src/Thread.cpp.o

client_src/Thread.i: client_src/Thread.cpp.i

.PHONY : client_src/Thread.i

# target to preprocess a source file
client_src/Thread.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Thread.cpp.i
.PHONY : client_src/Thread.cpp.i

client_src/Thread.s: client_src/Thread.cpp.s

.PHONY : client_src/Thread.s

# target to generate assembly for a file
client_src/Thread.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Thread.cpp.s
.PHONY : client_src/Thread.cpp.s

client_src/Zombie.o: client_src/Zombie.cpp.o

.PHONY : client_src/Zombie.o

# target to build an object file
client_src/Zombie.cpp.o:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Zombie.cpp.o
.PHONY : client_src/Zombie.cpp.o

client_src/Zombie.i: client_src/Zombie.cpp.i

.PHONY : client_src/Zombie.i

# target to preprocess a source file
client_src/Zombie.cpp.i:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Zombie.cpp.i
.PHONY : client_src/Zombie.cpp.i

client_src/Zombie.s: client_src/Zombie.cpp.s

.PHONY : client_src/Zombie.s

# target to generate assembly for a file
client_src/Zombie.cpp.s:
	$(MAKE) -f CMakeFiles/clientLib.dir/build.make CMakeFiles/clientLib.dir/client_src/Zombie.cpp.s
.PHONY : client_src/Zombie.cpp.s

client_src/client.o: client_src/client.cpp.o

.PHONY : client_src/client.o

# target to build an object file
client_src/client.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client_src/client.cpp.o
.PHONY : client_src/client.cpp.o

client_src/client.i: client_src/client.cpp.i

.PHONY : client_src/client.i

# target to preprocess a source file
client_src/client.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client_src/client.cpp.i
.PHONY : client_src/client.cpp.i

client_src/client.s: client_src/client.cpp.s

.PHONY : client_src/client.s

# target to generate assembly for a file
client_src/client.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client_src/client.cpp.s
.PHONY : client_src/client.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... clientLib"
	@echo "... client"
	@echo "... client_src/Banker.o"
	@echo "... client_src/Banker.i"
	@echo "... client_src/Banker.s"
	@echo "... client_src/BlockingMsgQueue.o"
	@echo "... client_src/BlockingMsgQueue.i"
	@echo "... client_src/BlockingMsgQueue.s"
	@echo "... client_src/Camera.o"
	@echo "... client_src/Camera.i"
	@echo "... client_src/Camera.s"
	@echo "... client_src/ClientConnector.o"
	@echo "... client_src/ClientConnector.i"
	@echo "... client_src/ClientConnector.s"
	@echo "... client_src/ClientController.o"
	@echo "... client_src/ClientController.i"
	@echo "... client_src/ClientController.s"
	@echo "... client_src/ClientProtocol.o"
	@echo "... client_src/ClientProtocol.i"
	@echo "... client_src/ClientProtocol.s"
	@echo "... client_src/Entity.o"
	@echo "... client_src/Entity.i"
	@echo "... client_src/Entity.s"
	@echo "... client_src/EntityManager.o"
	@echo "... client_src/EntityManager.i"
	@echo "... client_src/EntityManager.s"
	@echo "... client_src/Equippable.o"
	@echo "... client_src/Equippable.i"
	@echo "... client_src/Equippable.s"
	@echo "... client_src/EventManager.o"
	@echo "... client_src/EventManager.i"
	@echo "... client_src/EventManager.s"
	@echo "... client_src/ExpBar.o"
	@echo "... client_src/ExpBar.i"
	@echo "... client_src/ExpBar.s"
	@echo "... client_src/FilteredImage.o"
	@echo "... client_src/FilteredImage.i"
	@echo "... client_src/FilteredImage.s"
	@echo "... client_src/Goblin.o"
	@echo "... client_src/Goblin.i"
	@echo "... client_src/Goblin.s"
	@echo "... client_src/GraphicInventory.o"
	@echo "... client_src/GraphicInventory.i"
	@echo "... client_src/GraphicInventory.s"
	@echo "... client_src/Healer.o"
	@echo "... client_src/Healer.i"
	@echo "... client_src/Healer.s"
	@echo "... client_src/Image.o"
	@echo "... client_src/Image.i"
	@echo "... client_src/Image.s"
	@echo "... client_src/Item.o"
	@echo "... client_src/Item.i"
	@echo "... client_src/Item.s"
	@echo "... client_src/Layout.o"
	@echo "... client_src/Layout.i"
	@echo "... client_src/Layout.s"
	@echo "... client_src/LayoutManager.o"
	@echo "... client_src/LayoutManager.i"
	@echo "... client_src/LayoutManager.s"
	@echo "... client_src/LoginManager.o"
	@echo "... client_src/LoginManager.i"
	@echo "... client_src/LoginManager.s"
	@echo "... client_src/LoginScreen.o"
	@echo "... client_src/LoginScreen.i"
	@echo "... client_src/LoginScreen.s"
	@echo "... client_src/MainMap.o"
	@echo "... client_src/MainMap.i"
	@echo "... client_src/MainMap.s"
	@echo "... client_src/MainWindow.o"
	@echo "... client_src/MainWindow.i"
	@echo "... client_src/MainWindow.s"
	@echo "... client_src/MapImage.o"
	@echo "... client_src/MapImage.i"
	@echo "... client_src/MapImage.s"
	@echo "... client_src/Merchant.o"
	@echo "... client_src/Merchant.i"
	@echo "... client_src/Merchant.s"
	@echo "... client_src/MiniChat.o"
	@echo "... client_src/MiniChat.i"
	@echo "... client_src/MiniChat.s"
	@echo "... client_src/ModelController.o"
	@echo "... client_src/ModelController.i"
	@echo "... client_src/ModelController.s"
	@echo "... client_src/NPC.o"
	@echo "... client_src/NPC.i"
	@echo "... client_src/NPC.s"
	@echo "... client_src/OSError.o"
	@echo "... client_src/OSError.i"
	@echo "... client_src/OSError.s"
	@echo "... client_src/Player.o"
	@echo "... client_src/Player.i"
	@echo "... client_src/Player.s"
	@echo "... client_src/ProtMsgQueue.o"
	@echo "... client_src/ProtMsgQueue.i"
	@echo "... client_src/ProtMsgQueue.s"
	@echo "... client_src/QueueClosedException.o"
	@echo "... client_src/QueueClosedException.i"
	@echo "... client_src/QueueClosedException.s"
	@echo "... client_src/QuitException.o"
	@echo "... client_src/QuitException.i"
	@echo "... client_src/QuitException.s"
	@echo "... client_src/Receiver.o"
	@echo "... client_src/Receiver.i"
	@echo "... client_src/Receiver.s"
	@echo "... client_src/Renderer.o"
	@echo "... client_src/Renderer.i"
	@echo "... client_src/Renderer.s"
	@echo "... client_src/SDLError.o"
	@echo "... client_src/SDLError.i"
	@echo "... client_src/SDLError.s"
	@echo "... client_src/Sender.o"
	@echo "... client_src/Sender.i"
	@echo "... client_src/Sender.s"
	@echo "... client_src/Skeleton.o"
	@echo "... client_src/Skeleton.i"
	@echo "... client_src/Skeleton.s"
	@echo "... client_src/Socket.o"
	@echo "... client_src/Socket.i"
	@echo "... client_src/Socket.s"
	@echo "... client_src/SocketException.o"
	@echo "... client_src/SocketException.i"
	@echo "... client_src/SocketException.s"
	@echo "... client_src/SpriteClipCreator.o"
	@echo "... client_src/SpriteClipCreator.i"
	@echo "... client_src/SpriteClipCreator.s"
	@echo "... client_src/Spyder.o"
	@echo "... client_src/Spyder.i"
	@echo "... client_src/Spyder.s"
	@echo "... client_src/Text.o"
	@echo "... client_src/Text.i"
	@echo "... client_src/Text.s"
	@echo "... client_src/Texture.o"
	@echo "... client_src/Texture.i"
	@echo "... client_src/Texture.s"
	@echo "... client_src/Thread.o"
	@echo "... client_src/Thread.i"
	@echo "... client_src/Thread.s"
	@echo "... client_src/Zombie.o"
	@echo "... client_src/Zombie.i"
	@echo "... client_src/Zombie.s"
	@echo "... client_src/client.o"
	@echo "... client_src/client.i"
	@echo "... client_src/client.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

